services:
  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'rhitmo_hospede'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/data/mysql
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
volumes:
  mysql: