spring:
  application:
    name: rhitmo-hospede
  datasource:
    username: 'user'
    url: jdbc:mysql://localhost:3306/rhitmo-hospede
    password: 'password'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    open-in-view: false