CREATE TABLE tb_guest
(
    id    BIGINT AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    phone VARCHAR(20)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;